Repository XRTK/Oculus, pull requests merged in 2020-05, with the labels that each got.

#69 Fix exceptions when Oculus platform is unavailiable
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/Plugins/OculusApi.cs
Labels: Bug

#71 Added preview package capabilities
  .gitignore
  XRTK.Oculus/Assets/XRTK.Generated.meta
  XRTK.Oculus/Assets/XRTK.Generated/Oculus.meta
  XRTK.Oculus/Assets/XRTK.Generated/SymbolicLinkSettings.asset
  XRTK.Oculus/Assets/XRTK.Generated/SymbolicLinkSettings.asset.meta
  XRTK.Oculus/Packages/com.xrtk.oculus/package.json
  XRTK.Oculus/Packages/manifest.json
  azure-pipelines.yml
  azure_pipelines/common.yml
  azure_pipelines/stages/publish.yml
  azure_pipelines/stages/steps/build-docs.yml
  azure_pipelines/stages/steps/build-unity-player.yml
  azure_pipelines/stages/steps/export-package-seed.yml
  azure_pipelines/stages/steps/install-unity.yml
  azure_pipelines/stages/steps/return-unity-license.yml
  azure_pipelines/stages/steps/run-unity-tests.yml
  azure_pipelines/stages/steps/upm-package-info.yml
  azure_pipelines/stages/unity-build.yml
Labels: Enhancement, Ready for Review

#72 updated github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/request_for_information.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Enhancement, Ready for Review

#73 Add platform level to path
  XRTK.Oculus/Packages/com.xrtk.oculus/Editor/BuildTools/OculusManifestPreprocessor.cs
Labels: Ready for Review

#74 Fix/oculus plugin and manifest generation
  XRTK.Oculus/Packages/com.xrtk.oculus/Editor/BuildTools/OculusManifestPreprocessor.cs
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/Plugins/1.48.0/Android/OVRPlugin.aar.meta
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/Plugins/OculusApi.cs
Labels: Ready for Review
