Repository XRTK/Oculus, pull requests merged in 2020-04, with the labels that each got.

#48 Cleanup and consolidation of editor scripts into a single location
  .gitignore
  XRTK.Oculus/Packages/com.xrtk.oculus/Editor.meta
  XRTK.Oculus/Packages/com.xrtk.oculus/Editor/XRTK.Oculus.Editor.asmdef
  XRTK.Oculus/Packages/com.xrtk.oculus/Inspectors/BuildTools.meta
  XRTK.Oculus/Packages/com.xrtk.oculus/Inspectors/BuildTools/AndroidManifest.OVRSubmission.xml
  XRTK.Oculus/Packages/com.xrtk.oculus/Inspectors/BuildTools/AndroidManifest.OVRSubmission.xml.meta
  XRTK.Oculus/Packages/com.xrtk.oculus/Inspectors/BuildTools/OculusManifestPreprocessor.cs
  XRTK.Oculus/Packages/com.xrtk.oculus/Inspectors/BuildTools/OculusManifestPreprocessor.cs.meta
  XRTK.Oculus/Packages/com.xrtk.oculus/Inspectors/OculusEditorAssetLocator.cs
  XRTK.Oculus/Packages/com.xrtk.oculus/Inspectors/OculusEditorAssetLocator.cs.meta
Labels: Ready for Review

#55 Change requests for controller provider inspectors
  XRTK.Oculus/Packages/com.xrtk.oculus/Inspectors/OculusHandControllerDataProviderProfileInspector.cs
Labels: Ready for Review

#56 added initial platform definition for Oculus
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime.meta
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/OculusPlatform.cs
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/OculusPlatform.cs.meta
Labels: In Progress

#57 Oculus platform definition
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime.meta
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/OculusPlatform.cs
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/OculusPlatform.cs.meta
Labels: Ready for Review, enhancement

#60 only print api version when playing
  XRTK.Oculus/Packages/com.xrtk.oculus/OculusApi.cs
Labels: Ready for Review

#61 Fix deprecated hand tracking permission request ID warning
  XRTK.Oculus/Packages/com.xrtk.oculus/Inspectors/BuildTools/OculusManifestPreprocessor.cs
Labels: Ready for Review

#65 added guid references to all instanced types
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/OculusPlatform.cs
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/Providers/Controllers/BaseOculusController.cs
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/Providers/Controllers/OculusControllerDataProvider.cs
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/Providers/Controllers/OculusGoController.cs
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/Providers/Controllers/OculusHandControllerDataProvider.cs
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/Providers/Controllers/OculusRemoteController.cs
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/Providers/Controllers/OculusTouchController.cs
  XRTK.Oculus/Packages/com.xrtk.oculus/Runtime/Providers/OculusCameraDataProvider.cs
Labels: Ready for Review
